pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    environment {
        SONAR_HOST_URL = 'http://192.168.56.10:9000' // SonarQube URL
    }

    stages {

        stage('Checkout') {
            steps {
                dir('tp-foyer') {
                    deleteDir() // wipes everything including corrupted .git
                    git branch: 'main',
                        url: 'https://github.com/houssem22Chakroun/springboot.git'
                }
            }
        }

        stage('Build') {
            steps {
                dir('tp-foyer') {
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Maven Package') {
            steps {
                dir('tp-foyer') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        dir('tp-foyer') {
                            sh '''
                                mvn clean verify sonar:sonar \
                                  -DskipTests=true \
                                  -Dsonar.host.url=$SONAR_HOST_URL \
                                  -Dsonar.login=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 4, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        success { echo '✅ Build and SonarQube Quality Gate passed!' }
        failure { echo '❌ Build failed or Quality Gate failed!' }
    }
}
