pipeline {
    agent any

    tools {
        jdk 'JAVA_HOME'
        maven 'M2_HOME'
    }

    environment {
        SONAR_HOST_URL = 'http://192.168.56.10:9000' // SonarQube URL on your slave
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/houssem22Chakroun/springboot.git'
            }
        }

        stage('Build') {
            steps {
                dir('tp-foyer') { // make sure this is where your pom.xml is
                    sh 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Maven Package') {
            steps {
                dir('tp-foyer') {
                    sh 'mvn package -DskipTests'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'SonarQube', variable: 'SONAR_TOKEN')]) {
                        dir('tp-foyer') {
                            sh '''
                                mvn clean verify sonar:sonar \
                                  -DskipTests=true \
                                  -Dsonar.host.url=$SONAR_HOST_URL \
                                  -Dsonar.login=$SONAR_TOKEN
                            '''
                        }
                    }
                }
            }
        }
    }

    post {
        success { echo '✅ Build and SonarQube analysis succeeded!' }
        failure { echo '❌ Build or SonarQube analysis failed!' }
    }
}
